### ISSUE TITLE
"250.5M".human_size_to_numbe

### ISSUE THREAD

**Issue by rgaufman** [zedtux/human_size_to_number#2]
```
[4] pry(main)> "250.5M".human_size_to_number
=> nil
```

Unfortunately this is the size reported by lsblk, I don't have control of the format. Can you please add support for this? pretty please? :)

**Comment by zedtux** [comment]
Please open your issue on the new project's place: https://gitlab.com/zedtux/human_size_to_number.

You could also give a try by adding your scenario in the [spec/human_size_to_number/helper_spec.rb](https://gitlab.com/zedtux/human_size_to_number/-/blob/master/spec/human_size_to_number/helper_spec.rb) file and run `rspec` after having updated the gem's source code.

To be honest with you, I don't use that gem nowadays, therefore I'm not going to implement it.
